//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HidSmbusExample.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_HIDSMBUSEXAMPLE_DIALOG      102
#define ID_INDICATOR_DEVICE             103
#define ID_INDICATOR_STATUS             104
#define IDD_PROPPAGE_CONFIGURATION      106
#define IDD_PROPPAGE_DATA_TRANSFER      107
#define IDD_PROPPAGE_PIN_CONFIGURATION  108
#define IDD_PROPPAGE_CUSTOMIZE          109
#define IDR_MAINFRAME                   128
#define IDC_TAB_CTRL                    1000
#define IDC_COMBO_DEVICE_LIST           1002
#define IDC_CHECK_CONNECT               1004
#define IDC_EDIT_VID                    1007
#define IDC_EDIT_PID                    1008
#define IDC_STATIC_LIBRARY_VERSION      1008
#define IDC_EDIT_RELEASE_NUMBER         1009
#define IDC_STATIC_HID_LIBRARY_VERSION  1009
#define IDC_EDIT_PART_NUMBER            1010
#define IDC_EDIT_BIT_RATE               1010
#define IDC_EDIT_PATH                   1011
#define IDC_EDIT_ACK_ADDRESS            1011
#define IDC_EDIT_SERIAL                 1012
#define IDC_CHECK_AUTO_RESPOND          1012
#define IDC_EDIT_MANUFACTURER           1013
#define IDC_EDIT_WRITE_TIMEOUT          1013
#define IDC_EDIT_PRODUCT                1014
#define IDC_EDIT_READ_TIMEOUT           1014
#define IDC_EDIT_VERSION                1015
#define IDC_EDIT_RESPONSE_TIMEOUT       1015
#define IDC_BUTTON_GET_SMBUS_CONFIG     1016
#define IDC_BUTTON_SET_SMBUS_CONFIG     1017
#define IDC_BUTTON_GET_TIMEOUT          1018
#define IDC_BUTTON_SET_TIMEOUT          1019
#define IDC_EDIT_TRANSFER_RETRIES       1020
#define IDC_CHECK_SCL_LOW_TIMEOUT       1021
#define IDC_EDIT_SLAVE_ADDRESS          1021
#define IDC_EDIT_BYTES_TO_READ          1022
#define IDC_BUTTON_READ_REQUEST         1023
#define IDC_EDIT_ADDRESSED_SLAVE_ADDRESS 1024
#define IDC_EDIT_TARGET_ADDRESS         1025
#define IDC_EDIT_TARGET_ADDRESS_SIZE    1026
#define IDC_BUTTON_ADDRESS_READ_REQUEST 1027
#define IDC_EDIT_RECEIVE_DATA           1028
#define IDC_BUTTON_FORCE_READ_RESPONSE  1029
#define IDC_BUTTON_GET_READ_RESPONSE    1030
#define IDC_EDIT_TRANSMIT_DATA          1031
#define IDC_BUTTON_WRITE_REQUEST        1032
#define IDC_EDIT_ADDRESSED_BYTES_TO_READ 1033
#define IDC_BUTTON_GET_TRANSFER_STATUS  1034
#define IDC_BUTTON_CANCEL_TRANSFER      1035
#define IDC_EDIT_WRITE_SLAVE_ADDRESS    1036
#define IDC_CHECK_DIRECTION_GPIO_0      1037
#define IDC_EDIT_BYTES_TO_READ2         1037
#define IDC_EDIT_FORCE_BYTES_TO_READ    1037
#define IDC_CHECK_DIRECTION_GPIO_1      1038
#define IDC_CHECK_DIRECTION_GPIO_2      1039
#define IDC_CHECK_DIRECTION_GPIO_3      1040
#define IDC_CHECK_DIRECTION_GPIO_4      1041
#define IDC_CHECK_DIRECTION_GPIO_5      1042
#define IDC_CHECK_DIRECTION_GPIO_6      1043
#define IDC_CHECK_DIRECTION_GPIO_7      1044
#define IDC_CHECK_MODE_GPIO_0           1045
#define IDC_CHECK_MODE_GPIO_1           1046
#define IDC_CHECK_MODE_GPIO_2           1047
#define IDC_CHECK_MODE_GPIO_3           1048
#define IDC_CHECK_MODE_GPIO_4           1049
#define IDC_CHECK_MODE_GPIO_5           1050
#define IDC_CHECK_MODE_GPIO_6           1051
#define IDC_CHECK_MODE_GPIO_7           1052
#define IDC_BUTTON_GET_GPIO_CONFIG      1053
#define IDC_BUTTON_SET_GPIO_CONFIG      1054
#define IDC_BUTTON_READ_LATCH           1055
#define IDC_BUTTON_WRITE_LATCH          1056
#define IDC_CHECK_LATCH_GPIO_0          1057
#define IDC_CHECK_LATCH_GPIO_1          1058
#define IDC_BUTTON_RESET                1058
#define IDC_CHECK_LATCH_GPIO_2          1059
#define IDC_CHECK_VID                   1059
#define IDC_CHECK_LATCH_GPIO_3          1060
#define IDC_CHECK_LATCH_GPIO_4          1061
#define IDC_CHECK_PID                   1061
#define IDC_CHECK_LATCH_GPIO_5          1062
#define IDC_CHECK_LATCH_GPIO_6          1063
#define IDC_CHECK_POWER                 1063
#define IDC_CHECK_LATCH_GPIO_7          1064
#define IDC_EDIT_POWER                  1064
#define IDC_CHECK_POWER_MODE            1065
#define IDC_RADIO_BUS_POWER             1066
#define IDC_RADIO_SELF_POWER_VREG_DIS   1067
#define IDC_RADIO_SELF_POWER_VREG_EN    1068
#define IDC_CHECK_RELEASE_VERSION       1069
#define IDC_EDIT_RELEASE_VERSION_MSB    1070
#define IDC_EDIT_RELEASE_VERSION_LSB    1071
#define IDC_BUTTON_GET_USB_CONFIG       1072
#define IDC_BUTTON_SET_USB_CONFIG       1073
#define IDC_BUTTON_GET_MANUFACTURER     1080
#define IDC_BUTTON_SET_MANUFACTURER     1081
#define IDC_BUTTON_GET_PRODUCT          1082
#define IDC_BUTTON_SET_PRODUCT          1083
#define IDC_BUTTON_GET_SERIAL           1084
#define IDC_BUTTON_SET_SERIAL           1085
#define IDC_BUTTON_GET_LOCK             1086
#define IDC_BUTTON_SET_LOCK             1087
#define IDC_CHECK_LOCK_VID              1088
#define IDC_CHECK_LOCK_PID              1089
#define IDC_CHECK_LOCK_POWER            1090
#define IDC_CHECK_LOCK_POWER_MODE       1091
#define IDC_CHECK_LOCK_RELEASE_VERSION  1092
#define IDC_CHECK_LOCK_MANUFACTURER     1093
#define IDC_CHECK_LOCK_PRODUCT          1094
#define IDC_CHECK_LOCK_SERIAL           1095
#define IDC_CHECK_CLK_OUTPUT            1096
#define IDC_CHECK_TX_TOGGLE             1097
#define IDC_CHECK_RX_TOGGLE             1098
#define IDC_EDIT_CLK_DIV                1099
#define IDC_EDIT2                       1100
#define IDC_EDIT_CLK_FREQ               1100

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1101
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
